apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vault-restart
  name: vault-restart-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-restart-manager-role
subjects:
- kind: ServiceAccount
  name: vault-restart-controller-manager
  namespace: {{ .Release.Namespace }}
