apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vault-restart
  name: vault-restart-controller-manager
  namespace: {{ .Release.Namespace }}
