apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: release-namespace

resources:
- ../default
- ../prometheus

# Patch namespace references to use Helm release namespace
patches:
- target:
    kind: Namespace
  patch: |-
    - op: replace
      path: /metadata/name
      value: release-namespace
